name: PR checker

on: [push, pull_request]

jobs:
  lint_and_unittest:
    name: Run linter and unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        poetry-version: ["1.1.11"]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry ${{ matrix.poetry-version }}
      run: |
        python -m pip install poetry==${{ matrix.poetry-version }}
        poetry config virtualenvs.create false
    - name: Install dependencies
      run: poetry install --no-root
    - name: Linter
      run: flake8
    - name: Unit tests
      run: pytest
    - name: Docstrings checker
      run: pydocstyle
    - name: Typing checker
      run: mypy
